/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newtopic;

import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

import notwist.base.Category;
import notwist.base.Discussion;
import notwist.base.DiscussionImpl;
import notwist.base.User;
import notwist.database.DBCategory;
import notwist.database.DBDiscussionImpl;

/**
 *
 * @author emily
 */
public class newtopic_gui extends javax.swing.JFrame {

    /**
     * Creates new form Homepage_gui
     */
	 private User actualUser=null;
	 private JTable table;
    public newtopic_gui(User user, JTable table) {
        initComponents();
        this.actualUser = user;
        this.setVisible(true);
        this.table = table;
        
    }


	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        drag_panel = new javax.swing.JPanel();
        commands_panel = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        header_panel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        homepage_button = new javax.swing.JLabel();
        category_filter = new javax.swing.JComboBox<>();
        profile_icon = new javax.swing.JLabel();
        bell_icon = new javax.swing.JLabel();
        new_discussion = new javax.swing.JButton();
        search_field = new javax.swing.JTextField();
        search_button = new javax.swing.JButton();
        topic_panel = new javax.swing.JPanel();
        category = new javax.swing.JComboBox<>();
        category_label = new javax.swing.JLabel();
        title_label = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        textPreview_label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        preview_textarea = new javax.swing.JTextArea();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        preview_textarea1 = new javax.swing.JTextArea();
        notify_checkbox = new javax.swing.JCheckBox();
        post_button = new javax.swing.JButton();
        preview_button = new javax.swing.JButton();
        textPreview_label1 = new javax.swing.JLabel();
        rules_panel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        rules_area = new javax.swing.JTextArea();
        markups_panel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tips_panel = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        drag_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(0, 150, 0));
        exit.setText("X");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout commands_panelLayout = new javax.swing.GroupLayout(commands_panel);
        commands_panel.setLayout(commands_panelLayout);
        commands_panelLayout.setHorizontalGroup(
            commands_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, commands_panelLayout.createSequentialGroup()
                .addContainerGap(231, Short.MAX_VALUE)
                .addComponent(exit)
                .addGap(19, 19, 19))
        );
        commands_panelLayout.setVerticalGroup(
            commands_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(commands_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        drag_panel.add(commands_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, 260, 40));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        jSeparator1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jSeparator1.setMinimumSize(new java.awt.Dimension(50, 20));
        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 20));

        homepage_button.setFont(new java.awt.Font("Bauhaus 93", 0, 18)); // NOI18N
        homepage_button.setText("NOTWIST");

        category_filter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        category_filter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Generale", "Animali", "Film", "Musica", "Cose", "Altre cose", "Cose non cose" }));

        profile_icon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        profile_icon.setText("P");
        profile_icon.setToolTipText("Futura icona profilo");

        bell_icon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bell_icon.setText("B");
        bell_icon.setToolTipText("Futura icona notifica");

        new_discussion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        new_discussion.setText("Crea una nuova discussione");

        search_field.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        search_field.setText("Search..");
        search_field.setMargin(new java.awt.Insets(2, 2, 2, 3));
        search_field.setMinimumSize(new java.awt.Dimension(7, 23));

        search_button.setText("Go");
        search_button.setMaximumSize(new java.awt.Dimension(45, 25));
        search_button.setMinimumSize(new java.awt.Dimension(45, 25));
        search_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout header_panelLayout = new javax.swing.GroupLayout(header_panel);
        header_panel.setLayout(header_panelLayout);
        header_panelLayout.setHorizontalGroup(
            header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(header_panelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(header_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homepage_button)
                .addGap(30, 30, 30)
                .addComponent(category_filter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(search_field, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(search_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(new_discussion)
                .addGap(27, 27, 27)
                .addComponent(bell_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(profile_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        header_panelLayout.setVerticalGroup(
            header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, header_panelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(new_discussion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(homepage_button)
                        .addComponent(category_filter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(profile_icon)
                        .addComponent(bell_icon)
                        .addComponent(search_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(search_button, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        drag_panel.add(header_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 90));

        topic_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        category.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        topic_panel.add(category, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 11, -1, -1));

        category_label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        category_label.setText("Categoria:");
        topic_panel.add(category_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, -1, -1));

        title_label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        title_label.setText("Titolo:");
        topic_panel.add(title_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 55, -1, -1));

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        topic_panel.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 52, 679, -1));

        textPreview_label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textPreview_label.setText("Preview testo");
        topic_panel.add(textPreview_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 86, -1, -1));

        preview_textarea.setColumns(20);
        preview_textarea.setRows(5);
        jScrollPane1.setViewportView(preview_textarea);
        
        topic_panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 299, 760, 151));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        topic_panel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 257, 760, 10));

        preview_textarea1.setColumns(20);
        preview_textarea1.setRows(5);
        preview_textarea1.setEnabled(false);

        jScrollPane2.setViewportView(preview_textarea1);

        topic_panel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 111, 760, 135));

        notify_checkbox.setText("Notificami se rispondono");
        topic_panel.add(notify_checkbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

        post_button.setText("Posta");
        topic_panel.add(post_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 450, -1, -1));

        preview_button.setText("Preview");
        topic_panel.add(preview_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 450, -1, -1));

        textPreview_label1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textPreview_label1.setText("Testo");
        topic_panel.add(textPreview_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 271, -1, -1));

        drag_panel.add(topic_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 780, 490));

        rules_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)), "Regole della Community", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jScrollPane3.setEnabled(false);
        jScrollPane3.setOpaque(false);

        rules_area.setColumns(20);
        rules_area.setRows(5);
        rules_area.setText("Regole della community:\n1. Test larghezza frase per vedere come funziona.\n2. Test\n3. Test\n4. Test\n\nAltra roba qui.\n\n\n\nPiù giù per lunghezza.\n");
        rules_area.setEnabled(false);
        jScrollPane3.setViewportView(rules_area);

        javax.swing.GroupLayout rules_panelLayout = new javax.swing.GroupLayout(rules_panel);
        rules_panel.setLayout(rules_panelLayout);
        rules_panelLayout.setHorizontalGroup(
            rules_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rules_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        rules_panelLayout.setVerticalGroup(
            rules_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rules_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        drag_panel.add(rules_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 100, 260, 250));

        markups_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)), "Tips", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jScrollPane4.setEnabled(false);

        tips_panel.setColumns(20);
        tips_panel.setRows(5);
        tips_panel.setText("Altro test blablabla\nasdasdasdasd\nasdasd\nasdasdassdasdassdasd\nasdasdasdasd\nasdadasdassdasd\nadadasdasdasdasd\nasdasdasdasd\nasdadsasdasd.");
        tips_panel.setWrapStyleWord(true);
        tips_panel.setEnabled(false);
        jScrollPane4.setViewportView(tips_panel);

        javax.swing.GroupLayout markups_panelLayout = new javax.swing.GroupLayout(markups_panel);
        markups_panel.setLayout(markups_panelLayout);
        markups_panelLayout.setHorizontalGroup(
            markups_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(markups_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        markups_panelLayout.setVerticalGroup(
            markups_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(markups_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        drag_panel.add(markups_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 360, 260, 210));

        getContentPane().add(drag_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 580));
        
        drag_panel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
            	drag_panelMouseDragged(evt);
            }
        });
        drag_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
            	drag_panelMousePressed(evt);
            }
        });
        
        pack();
        
        
        
        //<Personalization> of GUI with Methods NOTWIST
        //############################################

        category.setModel(this.loadModel());
    
        post_button.addActionListener(e ->{
        	   Category cate = new DBCategory().getCategoryByName(category.getSelectedItem().toString());
        		String title = jTextField1.getText();
                String desc = preview_textarea.getText();
                Discussion disc = new DiscussionImpl(this.actualUser.getId(), title,desc, cate);
                new DBDiscussionImpl().createDiscussion(disc, cate);
                JOptionPane.showMessageDialog(null, title + "\nPublished");
                DefaultTableModel model = (DefaultTableModel)table.getModel();
                model.addRow(new Object[] {title,0,0,this.actualUser.getUsername()});
                table.setModel(model);
                dispose();
                
        });
        
        
      // Sync with text PREVIEW and text TEXT
        preview_textarea1.setEnabled(false);
        preview_textarea.addKeyListener(new KeyListener() {

			@Override
			public void keyTyped(KeyEvent e) {}

			@Override
			public void keyPressed(KeyEvent e) {}

			@Override
			public void keyReleased(KeyEvent e) { preview_textarea1.setText(preview_textarea.getText()); }
        	
        });
        
        
        
    }
    


    private void exitMouseClicked(java.awt.event.MouseEvent evt) {
        dispose();
    }

    private void search_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_buttonActionPerformed
        // TODO add your handling code here:
    }
    
    int xy;
    int xx;
	
    private void drag_panelMouseDragged(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }                                    
    private void drag_panelMousePressed(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }
    
//GEN-LAST:event_search_buttonActionPerformed
    
   
    

//    
//    public void start(final User user) {
//    /* Create and display the form */
//    	java.awt.EventQueue.invokeLater(new Runnable() {
//    		public void run() {
//    			new newtopic_gui(user);
//    		}
//    	});
//        	
//    	System.out.print(actualUser + "AAAAA");
//    }
//    
    
    private DefaultComboBoxModel<String> loadModel() {
    	DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
    	for(Category c : new DBCategory().getNameOfAllTheCategories().get()) {
    		model.addElement(c.getName());
    	}
    	return model;
    }
    

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(newtopic_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(newtopic_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(newtopic_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(newtopic_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new newtopic_gui().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bell_icon;
    private javax.swing.JComboBox<String> category;
    private javax.swing.JComboBox<String> category_filter;
    private javax.swing.JLabel category_label;
    private javax.swing.JPanel commands_panel;
    private javax.swing.JPanel drag_panel;
    private javax.swing.JLabel exit;
    private javax.swing.JPanel header_panel;
    private javax.swing.JLabel homepage_button;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel markups_panel;
    private javax.swing.JButton new_discussion;
    private javax.swing.JCheckBox notify_checkbox;
    private javax.swing.JButton post_button;
    private javax.swing.JButton preview_button;
    private javax.swing.JTextArea preview_textarea;
    private javax.swing.JTextArea preview_textarea1;
    private javax.swing.JLabel profile_icon;
    private javax.swing.JTextArea rules_area;
    private javax.swing.JPanel rules_panel;
    private javax.swing.JButton search_button;
    private javax.swing.JTextField search_field;
    private javax.swing.JLabel textPreview_label;
    private javax.swing.JLabel textPreview_label1;
    private javax.swing.JTextArea tips_panel;
    private javax.swing.JLabel title_label;
    private javax.swing.JPanel topic_panel;
    // End of variables declaration//GEN-END:variables
}
